# Requires ANDROID_HOME set to the path of your Android SDK.
android_sdk_repository(
  name = "androidsdk",
    api_level = 25,
    # Ensure that you have the build_tools_version below installed in the
    # SDK manager as it updates periodically.
    build_tools_version = "26.0.2",
    # Replace with path to Android SDK on your system
    path = "/home/sensen/Android/Sdk",

)


git_repository(
    name = 'gmaven_rules',
    remote = 'https://github.com/aj-michael/gmaven_rules',
    commit = '3f430f197ff1c96ec7a4794a2b9f81c521dc65fe',
)
load('@gmaven_rules//:gmaven.bzl', 'gmaven_rules')
gmaven_rules()

# Required for GenerateFirebaseXml tool.
maven_jar(
  name = "com_google_code_gson",
  artifact = "com.google.code.gson:gson:2.8.2",
)
